# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        HomeConstruct\UserBundle\Entity\Users: sha512

    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_PROFESSIONNEL:       [ROLE_USER]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email

    provider:     in_memory

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        check:
            pattern: ^/register/check-email
            security: false

        confirm:
            pattern: ^/register/confirm/
            security: false

        confirmed:
            pattern: ^/register/confirmed/
            security: false

        reset:
            pattern: ^/resetting/reset/
            security: false

        # signin:
        #     pattern: ^/utilisateur/creation
        #     security: false

        login:
            pattern: ^/login$
            security: false

        resetting:
            pattern: ^/resetting$
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: home_construct_projet_list
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret:     '%secret%'
#access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
# app/config/security.yml

